# Generated by cpp11: do not edit by hand

xoshiro_rng_alloc <- function(r_seed, n_generators) {
  .Call("_xoshiro_xoshiro_rng_alloc", r_seed, n_generators)
}

xoshiro_rng_size <- function(ptr) {
  .Call("_xoshiro_xoshiro_rng_size", ptr)
}

xoshiro_rng_jump <- function(ptr) {
  invisible(.Call("_xoshiro_xoshiro_rng_jump", ptr))
}

xoshiro_rng_long_jump <- function(ptr) {
  invisible(.Call("_xoshiro_xoshiro_rng_long_jump", ptr))
}

xoshiro_rng_unif_rand <- function(ptr, n) {
  .Call("_xoshiro_xoshiro_rng_unif_rand", ptr, n)
}

xoshiro_rng_norm_rand <- function(ptr, n) {
  .Call("_xoshiro_xoshiro_rng_norm_rand", ptr, n)
}

xoshiro_rng_runif <- function(ptr, n, r_min, r_max) {
  .Call("_xoshiro_xoshiro_rng_runif", ptr, n, r_min, r_max)
}

xoshiro_rng_rnorm <- function(ptr, n, r_mean, r_sd) {
  .Call("_xoshiro_xoshiro_rng_rnorm", ptr, n, r_mean, r_sd)
}

xoshiro_rng_rbinom <- function(ptr, n, r_size, r_prob) {
  .Call("_xoshiro_xoshiro_rng_rbinom", ptr, n, r_size, r_prob)
}

xoshiro_rng_rpois <- function(ptr, n, r_lambda) {
  .Call("_xoshiro_xoshiro_rng_rpois", ptr, n, r_lambda)
}

xoshiro_rng_state <- function(ptr) {
  .Call("_xoshiro_xoshiro_rng_state", ptr)
}
